server:
  port: 10001
  servlet:
      session:
        timeout: 15m
        cookie:
          name: JSESSIONID
spring:
  profiles:
    active: @profiles.active@
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  security:
    user:
      name: nidongde
      password: $2a$10$.QBDcTrIUminRxAV.7cNoeyphuSwAwmpIQzs31I8FWytdCOEao2Rq
  datasource:
    tomcat:
      initial-size: 8
      min-idle: 5
      max-idle: 10
      max-wait: 10000
      max-active: 120
      test-on-borrow: false
      test-while-idle: true
      validation-query: SELECT 1
      validation-query-timeout: 3
      min-evictable-idle-time-millis: 1800000
      time-between-eviction-runs-millis: 300000